### ISSUE TITLE
[Suggestion] Combine the teleport to faction home message into one

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions#299]
**Is your feature request related to a problem? Please describe.**

![Image](https://github.com/user-attachments/assets/4d751cd0-caa9-4754-a013-8754a3564ff7)

Two lines could really be combined into one
`Teleporting to faction home in X seconds`

**Comment by ToberoCat** [comment]
I think I fixed it with the other issue related to the teleport message

**Comment by Josh65-2201** [comment]
Using the 2.3 nightly build list as changed 2 days ago it still the same

![Image](https://github.com/user-attachments/assets/4d9d7143-a2ee-4d59-9ebb-69a3d0233b78)
